### ISSUE TITLE
Issue with Pathway Tools 25.5 when checking log

### ISSUE THREAD

**Issue by DafniGi** [AuReMe/mpwt#71]
There is an error with the check_pwt function when using Pathway Tools 25.5.

In the pathologic.log file the format has changed from:
"PGDB contains XXXX genes, XXXX polypeptides, XXXX base pathways, XXXX reactions, XXXX compounds"
to:
"PGDB contains XXXX classes and XXXXX instances: XXXX genes, XXXX polypeptides, XXXX base pathways, XXXX reactions, XXXX compounds, XXX publications"

**Comment by ArnaudBelcour** [comment]
Hi @DafniGi,

Thank you for the issue. I have pushed a commit in the branch [mpwt_0.7.0](https://github.com/AuReMe/mpwt/tree/mpwt_0.7.0) that should fixed this issue.

Best regards,
Arnaud Belcour.

**Comment by ArnaudBelcour** [comment]
This should have been fixed with the release of the 0.7.0 (#72).
