### ISSUE TITLE
bypass the genetic-elements.dat and organisms.dat creation

### ISSUE THREAD

**Issue by lcottret** [AuReMe/mpwt#79]
Hi !

I'm ready to use mpwt :-).
In my pipeline, I generated all the genetic-elements.dat and organism.dat. Is there a way in mpwt to bypass the creation of these files if they are present in the input folders ?

Ludo

**Comment by lcottret** [comment]
To be more concrete, I put information in organisms.dat that I can't deal with in mpwt. For instance, the name of the species that I want to display (e.g to add the strain), the copyright, etc...

**Comment by ArnaudBelcour** [comment]
Hi @lcottret,

In the current version (0.7.2) mpwt will rewrite the input files, so it is not possible.

But I have made changes in the branch mpwt 0.8.0, that should keep the input files provided and not rewrite them.

Can you test it?
A little warning: the version on the branch 0.8.0 is still in development, so I recommend to make copies of your file before testing it.

**Comment by lcottret** [comment]
Hi !

Thanks @ArnaudBelcour !

What is the easiest way to test the 0.8.0 version ? Is it possible to use pip ?

**Comment by ArnaudBelcour** [comment]
Hi,

I think the easiest way is to combine git and pip.

First, uninstall older version of mpwt with a `pip uninstall mpwt`.

Then clone the repository:

`git clone https://github.com/AuReMe/mpwt.git`

Move to the branch 0.8.0:

`cd mpwt`
`git checkout mpwt_0.8.0`

Then install it with pip:
`pip install .`

You can also add the `-e` (editable) option: `pip install -e .` With the `-e` option, pip will track the changes made on the git repository allowing to easily update to the new commits (in combination with `git pull`).
