### ISSUE TITLE
Issue mpwt delete and ptools cache ?

### ISSUE THREAD

**Issue by lcottret** [AuReMe/mpwt#81]
Hi,

After creating a new PGDB with mpwt, I deleted it with mpwt delete. If I immediately run the creation of the same PGDB, the pathologic log indicates that the PGDB already exists. However, if I launch the pathway-tools interface, the PDGB does not appear in the list of available databases and I can re-run the creation of the PDGDB without problem. 
Maybe the pathway-tools cache is removed only when the interface is launched...

Ludo

**Comment by lcottret** [comment]
ptools version : 26.0
mpwt version : 0.7.2

**Comment by ArnaudBelcour** [comment]
Hi,

This is strange as `mpwt delete` deletes the PGDB folder in ptools-local and the verification of the presence of a PGDB is made by looking at this same folder.

Can you post the complete command log with the phrase indicating that the PGDB already exists?

**Comment by lcottret** [comment]
Please forget it, I'm not able to reproduce this behaviour...
