### ISSUE TITLE
Pathway Tools is not in the Path, mpwt can not work without it.

### ISSUE THREAD

**Issue by ChenCongZ** [AuReMe/mpwt#83]
When I run this pipeline, it prompts me: Pathway Tools is not in the Path, mpwt can not work without it. How should I solve it?

**Comment by ArnaudBelcour** [comment]
Hi @ChenCongZ,

This message indicates that Pathway Tools executable (`pathway-tools`) is not available in the path environment variable. Have you installed Pathway Tools and add it to the path?

To add Pathway Tools to the path variable after its installation is explained in the readme:

https://github.com/AuReMe/mpwt#requirements

For Linux and macOS it is by using the following commands:

```bash
echo 'export PATH="$PATH:/your/install/directory/pathway-tools:"' >> ~/.bashrc
source ~/.bashrc
```

For Windows, you must add the path of the pathway tools folder to the `Environment Variables`. Open the `Environment Variables` window, select the ` Advanced system settings`, `Environment Variables`. Then crate a new variables in the `System variable`.

But mpwt has not been tested on Windows, so I do not know if it works.

**Comment by ChenCongZ** [comment]
Dear Mr AuReMe,
I run it in the window and put it in the System variable. Please check below.
![QQ浏览器截图20221114202705](https://user-images.githubusercontent.com/98649346/201660405-203496d0-bf0a-4e40-b25e-d68fffa7d25e.png)

**Comment by ChenCongZ** [comment]
Hi @ArnaudBelcour,
Its installation location is C:\Program Files\Pathway Tools according to https://github.com/AuReMe/mpwt#requirements. So it must be my installation problem or its path setting problem. However, I also tried many changes. No key problem was found.

**Comment by ChenCongZ** [comment]
I tried it, too.
![QQ浏览器截图20221114205503](https://user-images.githubusercontent.com/98649346/201665701-b88cb025-34fe-490b-96ad-2ba201896c72.png)

**Comment by ChenCongZ** [comment]
detailed information:
![QQ浏览器截图20221114211800](https://user-images.githubusercontent.com/98649346/201670189-9e866e4d-1baa-431e-89e8-eb95337f892b.png)

**Comment by ArnaudBelcour** [comment]
I think there is no problem with your installation of Pathway Tools.

For your environment variable, I think that there is an issue. The variable column (变量) of the `System variable` window must be `path` to add the path of Pathway Tools and not `C:\Program Files\Pathway Tools` to have access to the executable files in the path. But this will give access to the path to executables such as `ptools.bat` and at this time mpwt does not handle these scripts (and I am not sure if it will handle them one day). Especially since I do not have the time to make these modifications.

As I have explained in my first post, we tested and used mpwt only on Linux and macOS. On Windows, I have only used using the [Windows Subsystem for Linux](https://learn.microsoft.com/en-us/windows/wsl/install) (by installing the Ubuntu subsystem on it and then installing the Pathway Tools installer associated with Linux), otherwise I do not think that mpwt can work with the powershell.

**Comment by ChenCongZ** [comment]
Hi @ArnaudBelcour ，
Thank you for your help.
This problem occurred when I installed Pathway Tools, and I suspect that my window system can't read it. However, I have tried many methods, but I can't find the key installation problem. Can you check it for me?
![QQ截图20221115190345](https://user-images.githubusercontent.com/98649346/201904334-02557968-1183-4cc2-8fc8-febcdfa6107c.png)


Warning: EnableWindow: (error 127) 找不到指定的程序(The specified program could not be found).

**Comment by ChenCongZ** [comment]
I made the changes according to your suggestion.
![QQ截图20221115190814](https://user-images.githubusercontent.com/98649346/201905267-35d3f9a7-13e8-45e4-a236-5707b8981374.png)

**Comment by ChenCongZ** [comment]
Hi @ArnaudBelcour ,
Thank you for your help. I have solved the problem of the path. Can you tell me the version of the Pathway Tools used in testing "Metage2Metabo\test\metabolic_data\toy_bact"

**Comment by ChenCongZ** [comment]
Because I want to get toy_bact SMBL format in testing "Metage2Metabo\test\metabolic_data\toy_bact"

**Comment by ChenCongZ** [comment]
Hi @ArnaudBelcour, 
This problem always occurs when I run Mpwt.
mpwt.multiprocess_pwt(input_folder='bacteria',patho_inference=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\chencong\AppData\Local\Programs\Python\Python39\lib\site-packages\mpwt\mpwt_workflow.py", line 79, in multiprocess_pwt
    error = utils.check_ptools_local_pwt()
  File "C:\Users\chencong\AppData\Local\Programs\Python\Python39\lib\site-packages\mpwt\utils.py", line 61, in check_ptools_local_pwt
    ptools_path = find_ptools_path()
  File "C:\Users\chencong\AppData\Local\Programs\Python\Python39\lib\site-packages\mpwt\utils.py", line 46, in find_ptools_path
    ptools_local_str = [line for line in pathway_tools_file if 'PTOOLS_LOCAL_PATH' in line][0]
  File "C:\Users\chencong\AppData\Local\Programs\Python\Python39\lib\site-packages\mpwt\utils.py", line 46, in <listcomp>
    ptools_local_str = [line for line in pathway_tools_file if 'PTOOLS_LOCAL_PATH' in line][0]
  File "C:\Users\chencong\AppData\Local\Programs\Python\Python39\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 2: invalid start byte

**Comment by ArnaudBelcour** [comment]
Hi @ChenCongZ,

I do not think that the error comes from your installation of Pathway Tools.
mpwt is not working on Windows (as the binary and paths seem to be different from the ones of the Linux/macOS versions) and I have not the time and resource to work on this.

**Comment by ChenCongZ** [comment]
Hi @ArnaudBelcour,
Thank you for your suggestion!
Recently I tried to solve these problems with ubuntu ( linux operating system) and got some progress. At the same time, I encountered some problems in the mpwt pipeline. It shown below:


![Screenshot from 2022-11-25 10-51-46](https://user-images.githubusercontent.com/98649346/203891830-1cd62f2b-ec35-4db0-aa93-05a04c0d30fd.jpg)

**Comment by ChenCongZ** [comment]
I used your data to  get some results in the mpwt, but I have a question: I get XML data format like this, not the same as you get.Does this have an impact on M2M pipeline analysis?
![Screenshot from 2022-11-25 19-41-53](https://user-images.githubusercontent.com/98649346/203979977-4c5b8f82-78e9-4ea1-ad4a-a3b622d64f9d.png)
![Screenshot from 2022-11-25 19-42-17](https://user-images.githubusercontent.com/98649346/203980017-bada5b31-d8e9-47b2-b16a-d1827fc9e51e.png)

**Comment by ArnaudBelcour** [comment]
Hi @ChenCongZ,

For the first issue, it comes from the `taxon_id.tsv` file (for more information look at the [readme](https://github.com/AuReMe/mpwt#taxon-id-tsv-file)). There are issues in the format, this file must look like:

| Column 1 (ID) | Column 2 (taxonomic ID) |
|---------------------------|---------------------------|
| bin_1          | 562                       |

The taxonomic ID corresponds to the taxonomic ID associated with your organism in the [NCBI taxonomy database](https://www.ncbi.nlm.nih.gov/taxonomy). For example, here 562 corresponds to _Escherichia coli_.

For the XML files you created, yes this will impact Metag2Metabo results. You created these files using the `--mx` (in command line) or the `xml_extraction` (in python) option. This extracts XML files created by Pathway Tools. These files are different from the ones created by Metage2Metabo as they are created by the padmet package.
There are multiple differences such as different IDs, the XML from Pathway Tools will contain instantiated metabolites from metabolite class whereas SBML from padmet will only contained the classes.

If you use this as a test to find similar results, you need either to give the flat files (obtained with `--md` or `dat_extraction`) to Metage2Metabo or to launch Metage2Metabo with `recon` on your the same folder.

**Comment by ChenCongZ** [comment]
Hi @ArnaudBelcour,
Thank you for your suggestion!
This prompt came up today when I reconstructed the metabolic network model of the test data based on your reminder. However, I don't know which step I overlooked.

>>> reconstruction.recon('/home/chencong/test','/home/chencong/output3',noorphan_bool=True,padmet_bool=False,sbml_level={2},nb_cpu=2,clean=True,use_pwt_xml=True)
CRITICAL:metage2metabo.m2m.reconstruction:No /home/chencong/.ncbirc file, please fix it before using the program

**Comment by ChenCongZ** [comment]
I also checked its status.
chencong@chencong-QiTianM428-A606:~$ ls -l /home/chencong/.bashrc
-rw-rw-rw- 1 chencong chencong 4027 Nov 26 10:58 /home/chencong/.bashrc

**Comment by ChenCongZ** [comment]
Hi @Arnaud Belcour,
AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getchildren'.
![Screenshot from 2022-11-26 21-25-21](https://user-images.githubusercontent.com/98649346/204091371-0d5bd5cb-a8ae-4bce-b927-c56745d0daab.png)

**Comment by ChenCongZ** [comment]
Hi @ArnaudBelcour,
I'm very sorry to bother you when you are busy, but I have encountered many problems during the reconstruction of metabolic pathway in a few days. I can solve some of them, but my limited ability can't solve all of them. I'm confused that I reconstructed metabolic pathway data by directly using the data annotated by prokka after binning. The annotated file (.gbk) of an organism is divided into several sections, and the specific files are listed below. Can files like this be directly used for data input without m2m? 
[bin.4.strict.txt](https://github.com/AuReMe/mpwt/files/10121352/bin.4.strict.txt)

**Comment by ArnaudBelcour** [comment]
Hi @ChenCongZ,

Yes this file can be used as input for mpwt/m2m. You need to change its extension (from `txt` to `gbff`). Furthermore, you need to use a taxon_id file to indicate the taxon ID corresponding to this file as there is no taxonomic information in the gbff file created by Prokka.
The different sections in the gbff file (called Locus) correspond to the different contig contained inside this bin, Pathway Tools will handle them without problems.

**Comment by ChenCongZ** [comment]
Hi @ArnaudBelcour,
Thank you for your help.
I've got the single species sbml file.
But I encountered a problem converting seeds metabolites file.
![Screenshot from 2022-12-01 15-02-02](https://user-images.githubusercontent.com/98649346/204987749-9fc4e8f9-30ca-4a8b-ac42-aaa840f22213.png)

**Comment by ChenCongZ** [comment]
Hi @ArnaudBelcour,
Thank you for your help.
I've fixed these issues, thank you for your help.

**Comment by ChenCongZ** [comment]
Hi @ArnaudBelcour,
I can run all the other results,but there is a issue about m2m.recon.
![Screenshot from 2022-12-01 22-44-52](https://user-images.githubusercontent.com/98649346/205083240-4226fe47-0a2d-4391-bd65-bda7677e5f1d.png)
