### ISSUE TITLE
When I use pathway tools to build models, this problem always appears: Fatal error: The search using the name of your rganism ("Caloramator Bacteria, Firmicutes, Clostridia, Clostridiales, Caloramator." strain=NIL) failed to find any Taxon class for your organism or returned ambiguous results.

### ISSUE THREAD

**Issue by ChenCongZ** [AuReMe/mpwt#86]
Hi @ArnaudBelcour,
  When I use pathway tools to build models, this problem always appears: Fatal error: The search using the name of your organism ("Caloramator Bacteria, Firmicutes, Clostridia, Clostridiales, Caloramator." strain=NIL) failed to find any Taxon class for your organism or returned ambiguous results. Please revise your organism-params.dat file to specify an NCBI Taxonomy ID or a valid domain for your organism GCA_002400085. But I read my file and it seems to correspond to the NCBI classification. Can you show me where my problem is? The compressed package contains the information when I created it. The compressed package contains the information when I created it.
[model.zip](https://github.com/AuReMe/mpwt/files/12022461/model.zip)

**Comment by ArnaudBelcour** [comment]
Hi @ChenCongZ,

There is an issue in your genbank files that leads to this error. In the line below `ORGANISM` (containing the taxonomy associated with your organism), you have a string with taxa names separated by `,` whereas it should be `;`.

Your input that leads to the error (for file `GCA_002400085.gbk`):

```
SOURCE      Caloramator
  ORGANISM  Caloramator
            Bacteria, Firmicutes, Clostridia, Clostridiales, Caloramator.
```

The correct input:
```
SOURCE      Caloramator
  ORGANISM  Caloramator
            Bacteria; Firmicutes; Clostridia; Clostridiales; Caloramator.
```

Also as you have `taxon_id.tsv`, you could use the `--taxon-id` option to directly use the taxon ID contains in these files, that should avoid this issue. But before you should remove the `organism-params.dat` files in your folder as they are not correct.

**Comment by ChenCongZ** [comment]
Hi @ArnaudBelcour,
   Thank you for your help. Solve this problem and close it.
